permalink: /:title/
plugins:
  - jekyll-sitemap

title: niclaskron.net
url: https://niclaskron.net
baseurl: ""
description: "Personal website of Niclas"
author: Niclas
twitter: kankroon
stackoverflow: 2352843/niclas
linkedin: 
bitbucket:
goodreads:
delicious:
hackernews:
medium:
github: sphrak
youtube:
500px:
irc: aresfour
ircchannel: archlinux # a channel that you are frequenting
username: aresfour
email: niclas.kroon@gmail.com
timezone: Europe/Stockholm
